config/routes.rb
Muschool::Application.routes.draw do

  resources :plushkis

  resources :infos

  resources :tenders

  resources :walls

  resources :funds

  resources :rewards

  resources :prizes

  resources :cities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "gallery" => "pages#gallery", :as => "gallery"
  resources :users
  resources :sessions

  root :to => 'pages#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many   :users
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many   :users
end

app/models/fund.rb
class Fund < ActiveRecord::Base
    validates_presence_of :taction
    validates_presence_of :gold
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/info.rb
class Info < ActiveRecord::Base
    validates_presence_of :location
  validates_uniqueness_of :location
end

app/models/mission.rb
class Mission < ActiveRecord::Base
    has_many   :users
end

app/models/plushki.rb
class Plushki < ActiveRecord::Base
      validates_presence_of :sum
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  has_many :rewards, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :image
end

app/models/profession.rb
class Profession < ActiveRecord::Base
    has_many   :users
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_one    :prize
  belongs_to :prize  # foreign key - prize_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/tender.rb
class Tender < ActiveRecord::Base
  validates_length_of :img, :minimum => 10
  validates_presence_of :img
  
  validates_length_of :comment, :maximum => 300
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope :order => 'email ASC'
  
  has_secure_password
  validates_presence_of :password, :on => :create, :message => "Can't be blank"
  validates_presence_of :email 
  validates_presence_of :name
  validates_presence_of :mission_id
  validates_presence_of :character_id
  validates_presence_of :profession_id
  validates_presence_of :city_id
  validates_presence_of :level
  validates_presence_of :maxhealth
  validates_presence_of :craft
  validates_uniqueness_of :email
  validates_inclusion_of :level, :in => 0..120,
             :message => "Nononono"
  validates_inclusion_of :maxhealth, :in => 0..20000,
             :message => "Nononono"
  validates_inclusion_of :craft, :in => 0..650,
             :message => "Nononono"
  
  has_one    :mission
  has_one    :character
  has_one    :profession
  has_one    :city
  belongs_to :mission     # foreign key - mission_id
  belongs_to :character     # foreign key - character_id
  belongs_to :profession     # foreign key - profession_id
  belongs_to :city     # foreign key - city_id
  
  has_many :rewards, :dependent => :destroy 
  has_many :funds, :dependent => :destroy 
  has_many :plushkis, :dependent => :destroy 
  has_many :walls, :dependent => :destroy 
  has_many :tenders, :dependent => :destroy 
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  default_scope :order => 'created_at DESC'
  
  validates_presence_of :post
  validates_presence_of :user_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
  
  validates_length_of :post, :maximum => 300
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(params[:reward])

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render json: @reward, status: :created, location: @reward }
      else
        format.html { render action: "new" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plushkis_helper.rb
module PlushkisHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/rewards/_form.html.erb
<% if current_user && admin_user %>
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, User.all, :id, :email %>
  </div>
  <div class="field">
    <%= f.label :prize_id %><br />
    <%= f.collection_select :prize_id, Prize.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit "Наградить!"%>
  </div>
<% end %>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <tr>
    <th>User</th>
    <th>Prize</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.user.email %></td>
    <td><%= reward.prize.title %></td>
    <td><%= reward.text %></td>
    <td><%= link_to 'Show', reward %></td>
    <% if current_user && admin_user %>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if current_user && admin_user %>
<%= link_to 'New Reward', new_reward_path %>
<% end %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<h2>Наградной сертификат</h2>

<div class="span-4 border">
	<div style="text-align: center;"><b><%= link_to @reward.prize.title, @reward.prize %></b></div>
	<div style="text-align: center;"><%= link_to image_tag(@reward.prize.image), @reward.prize %></div>

</div>
<div class="span-20 last">
<p>
  <b>Награжден:</b>
  <%= link_to @reward.user.email, @reward.user %>
</p>

<p>
  <b>Основание:</b>
  <%= @reward.text %>
</p>

<p>
  <b>Получена:</b>
  <%= @reward.created_at.strftime('%d.%m.%Y ') %>
</p>
<% if current_user && admin_user %>
<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>
<% end %>
</div>