config/routes.rb
Muschool::Application.routes.draw do

  resources :plushkis

  resources :infos

  resources :tenders

  resources :walls

  resources :funds

  resources :rewards

  resources :prizes

  resources :cities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "gallery" => "pages#gallery", :as => "gallery"
  resources :users
  resources :sessions

  root :to => 'pages#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many   :users
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many   :users
end

app/models/fund.rb
class Fund < ActiveRecord::Base
    validates_presence_of :taction
    validates_presence_of :gold
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/info.rb
class Info < ActiveRecord::Base
    validates_presence_of :location
  validates_uniqueness_of :location
end

app/models/mission.rb
class Mission < ActiveRecord::Base
    has_many   :users
end

app/models/plushki.rb
class Plushki < ActiveRecord::Base
      validates_presence_of :sum
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  has_many :rewards, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :image
end

app/models/profession.rb
class Profession < ActiveRecord::Base
    has_many   :users
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_one    :prize
  belongs_to :prize  # foreign key - prize_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/tender.rb
class Tender < ActiveRecord::Base
  validates_length_of :img, :minimum => 10
  validates_presence_of :img
  
  validates_length_of :comment, :maximum => 300
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope :order => 'email ASC'
  
  has_secure_password
  validates_presence_of :password, :on => :create, :message => "Can't be blank"
  validates_presence_of :email 
  validates_presence_of :name
  validates_presence_of :mission_id
  validates_presence_of :character_id
  validates_presence_of :profession_id
  validates_presence_of :city_id
  validates_presence_of :level
  validates_presence_of :maxhealth
  validates_presence_of :craft
  validates_uniqueness_of :email
  validates_inclusion_of :level, :in => 0..120,
             :message => "Nononono"
  validates_inclusion_of :maxhealth, :in => 0..20000,
             :message => "Nononono"
  validates_inclusion_of :craft, :in => 0..650,
             :message => "Nononono"
  
  has_one    :mission
  has_one    :character
  has_one    :profession
  has_one    :city
  belongs_to :mission     # foreign key - mission_id
  belongs_to :character     # foreign key - character_id
  belongs_to :profession     # foreign key - profession_id
  belongs_to :city     # foreign key - city_id
  
  has_many :rewards, :dependent => :destroy 
  has_many :funds, :dependent => :destroy 
  has_many :plushkis, :dependent => :destroy 
  has_many :walls, :dependent => :destroy 
  has_many :tenders, :dependent => :destroy 
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  default_scope :order => 'created_at DESC'
  
  validates_presence_of :post
  validates_presence_of :user_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
  
  validates_length_of :post, :maximum => 300
end

app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  # GET /tenders
  # GET /tenders.json
  def index
    @tenders = Tender.all.sort_by{ rand }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tenders }
    end
  end

  # GET /tenders/1
  # GET /tenders/1.json
  def show
    @tender = Tender.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tender }
    end
  end

  # GET /tenders/new
  # GET /tenders/new.json
  def new
    @tender = Tender.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tender }
    end
  end

  # GET /tenders/1/edit
  def edit
    @tender = Tender.find(params[:id])
  end

  # POST /tenders
  # POST /tenders.json
  def create
    @tender = Tender.new(params[:tender])
    @tender.user_id = current_user.id
    respond_to do |format|
      if @tender.save
        format.html { redirect_to @tender, notice: 'Tender was successfully created.' }
        format.json { render json: @tender, status: :created, location: @tender }
      else
        format.html { render action: "new" }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tenders/1
  # PUT /tenders/1.json
  def update
    @tender = Tender.find(params[:id])

    respond_to do |format|
      if @tender.update_attributes(params[:tender])
        format.html { redirect_to @tender, notice: 'Tender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenders/1
  # DELETE /tenders/1.json
  def destroy
    @tender = Tender.find(params[:id])
    @tender.destroy

    respond_to do |format|
      format.html { redirect_to tenders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plushkis_helper.rb
module PlushkisHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/tenders/_form.html.erb
<%= form_for(@tender, :html => { :class => "form-stacked" }) do |f| %>
  <% if @tender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tender.errors.count, "error") %> prohibited this tender from being saved:</h2>

      <ul>
      <% @tender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Изображение %>
    <%= f.text_field :img, :class => "span10", :placeholder => "http://site.ru/blablabla/kartinko.jpg" %>
  </div>
  <div class="field">
    <%= f.label :Комментарий %>
    <%= f.text_field :comment, :class => "span10", :placeholder => "немного о работе, до 300 символов" %>
  </div>
  <br />
    *для загрузки картинок можно использовать сервисы <%=link_to "SavePic", "http://savepic.ru/"%> или <%=link_to "Radikal", "http://www.radikal.ru/"%> 
  <br />
  <hr>
  <div>
    <%= f.submit "Тадам!", :class => "btn primary"%>
  </div>
  
  
<% end %>

app/views/tenders/edit.html.erb
<h1>Редактирование работы</h1>

<%= render 'form' %>

<%= link_to 'К работе', @tender %> |
<%= link_to 'Ко всем работам', tenders_path %>

app/views/tenders/index.html.erb
<% if current_user %>
<h1>Все работы  <div style="float: right;"><%= link_to 'Добавить свою работу!', new_tender_path, :class => "btn success" if current_user %></div></h1>

<% if Info.where(:location => 2).first %>
<div class="alert-message block-message success">
	<a class="close" href="#">&times;</a>
<%= raw(Info.where(:location => 2).first.text) %>
</div>
<%end%>

<div class="row">
<% @tenders.each do |tender| %>
  <div class="span4" style="min-height: 300px;">
   
    <div style="text-align: center;"><%= link_to tender.user.email, tender.user %> <% if admin_user or (current_user.id == tender.user.id)%><%= link_to 'x', tender, confirm: 'Точно удалить работу?', method: :delete %><%end%></div>
     <div class="media-grid"><%= link_to image_tag(tender.img, :class => "avatar2"), tender %></div>
    

    
  </div>
<% end %>
</table>
</div>
<%else%>
<%= render "layouts/auth"%>
<%end%>

app/views/tenders/new.html.erb
<h1>Добавление новой работы</h1>

<%= render 'form' %>

<%= link_to 'Обратно', tenders_path %>

app/views/tenders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h4>Работа от <%= link_to @tender.user.email, @tender.user %></h4>
</p>
<p>
  <%= @tender.comment %>
</p>
<p>
  <%= image_tag @tender.img %>
</p>





<% if admin_user or (current_user.id == @tender.user.id)%>
<%= link_to 'Редактировать', edit_tender_path(@tender) %> |
<%end%>
<%= link_to 'Ко всем работам', tenders_path %>