config/routes.rb
Muschool::Application.routes.draw do

  resources :plushkis

  resources :infos

  resources :tenders

  resources :walls

  resources :funds

  resources :rewards

  resources :prizes

  resources :cities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "gallery" => "pages#gallery", :as => "gallery"
  resources :users
  resources :sessions

  root :to => 'pages#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many   :users
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many   :users
end

app/models/fund.rb
class Fund < ActiveRecord::Base
    validates_presence_of :taction
    validates_presence_of :gold
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/info.rb
class Info < ActiveRecord::Base
    validates_presence_of :location
  validates_uniqueness_of :location
end

app/models/mission.rb
class Mission < ActiveRecord::Base
    has_many   :users
end

app/models/plushki.rb
class Plushki < ActiveRecord::Base
      validates_presence_of :sum
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  has_many :rewards, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :image
end

app/models/profession.rb
class Profession < ActiveRecord::Base
    has_many   :users
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_one    :prize
  belongs_to :prize  # foreign key - prize_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/tender.rb
class Tender < ActiveRecord::Base
  validates_length_of :img, :minimum => 10
  validates_presence_of :img
  
  validates_length_of :comment, :maximum => 300
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope :order => 'email ASC'
  
  has_secure_password
  validates_presence_of :password, :on => :create, :message => "Can't be blank"
  validates_presence_of :email 
  validates_presence_of :name
  validates_presence_of :mission_id
  validates_presence_of :character_id
  validates_presence_of :profession_id
  validates_presence_of :city_id
  validates_presence_of :level
  validates_presence_of :maxhealth
  validates_presence_of :craft
  validates_uniqueness_of :email
  validates_inclusion_of :level, :in => 0..120,
             :message => "Nononono"
  validates_inclusion_of :maxhealth, :in => 0..20000,
             :message => "Nononono"
  validates_inclusion_of :craft, :in => 0..650,
             :message => "Nononono"
  
  has_one    :mission
  has_one    :character
  has_one    :profession
  has_one    :city
  belongs_to :mission     # foreign key - mission_id
  belongs_to :character     # foreign key - character_id
  belongs_to :profession     # foreign key - profession_id
  belongs_to :city     # foreign key - city_id
  
  has_many :rewards, :dependent => :destroy 
  has_many :funds, :dependent => :destroy 
  has_many :plushkis, :dependent => :destroy 
  has_many :walls, :dependent => :destroy 
  has_many :tenders, :dependent => :destroy 
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  default_scope :order => 'created_at DESC'
  
  validates_presence_of :post
  validates_presence_of :user_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
  
  validates_length_of :post, :maximum => 300
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plushkis_helper.rb
module PlushkisHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/infos/_form.html.erb
<%if admin_user%>
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text, :size => "80x20" %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.number_field :location %>
  </div>
  *1 - главная, 2 - тендеры, 3 — перекач, 4 — плюшкин.
  <div>
    <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<%if admin_user%>
<h1>Listing infos</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.text %></td>
    <td><%= info.location %></td>
    <td><%= link_to 'Show', info %></td>
    <td><%= link_to 'Edit', edit_info_path(info) %></td>
    <td><%= link_to 'Destroy', info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Info', new_info_path %>
<%end%>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @info.text %>
</p>

<p>
  <b>Location:</b>
  <%= @info.location %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>