config/routes.rb
Muschool::Application.routes.draw do

  resources :plushkis

  resources :infos

  resources :tenders

  resources :walls

  resources :funds

  resources :rewards

  resources :prizes

  resources :cities

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "gallery" => "pages#gallery", :as => "gallery"
  resources :users
  resources :sessions

  root :to => 'pages#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many   :users
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many   :users
end

app/models/fund.rb
class Fund < ActiveRecord::Base
    validates_presence_of :taction
    validates_presence_of :gold
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/info.rb
class Info < ActiveRecord::Base
    validates_presence_of :location
  validates_uniqueness_of :location
end

app/models/mission.rb
class Mission < ActiveRecord::Base
    has_many   :users
end

app/models/plushki.rb
class Plushki < ActiveRecord::Base
      validates_presence_of :sum
    validates_presence_of :user_id

  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  has_many :rewards, :dependent => :destroy
  validates_presence_of :title
  validates_presence_of :image
end

app/models/profession.rb
class Profession < ActiveRecord::Base
    has_many   :users
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_one    :prize
  belongs_to :prize  # foreign key - prize_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/tender.rb
class Tender < ActiveRecord::Base
  validates_length_of :img, :minimum => 10
  validates_presence_of :img
  
  validates_length_of :comment, :maximum => 300
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope :order => 'email ASC'
  
  has_secure_password
  validates_presence_of :password, :on => :create, :message => "Can't be blank"
  validates_presence_of :email 
  validates_presence_of :name
  validates_presence_of :mission_id
  validates_presence_of :character_id
  validates_presence_of :profession_id
  validates_presence_of :city_id
  validates_presence_of :level
  validates_presence_of :maxhealth
  validates_presence_of :craft
  validates_uniqueness_of :email
  validates_inclusion_of :level, :in => 0..120,
             :message => "Nononono"
  validates_inclusion_of :maxhealth, :in => 0..20000,
             :message => "Nononono"
  validates_inclusion_of :craft, :in => 0..650,
             :message => "Nononono"
  
  has_one    :mission
  has_one    :character
  has_one    :profession
  has_one    :city
  belongs_to :mission     # foreign key - mission_id
  belongs_to :character     # foreign key - character_id
  belongs_to :profession     # foreign key - profession_id
  belongs_to :city     # foreign key - city_id
  
  has_many :rewards, :dependent => :destroy 
  has_many :funds, :dependent => :destroy 
  has_many :plushkis, :dependent => :destroy 
  has_many :walls, :dependent => :destroy 
  has_many :tenders, :dependent => :destroy 
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  default_scope :order => 'created_at DESC'
  
  validates_presence_of :post
  validates_presence_of :user_id
  
  has_one    :user
  belongs_to :user   # foreign key - user_id
  
  validates_length_of :post, :maximum => 300
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/_auth.html.erb
<div class="alert-message block-message warning">
	<a class="close" href="#">&times;</a>
<h3>Для доступа к разделу необходимо авторизироваться на сайте</h3>
			<div class="alert-actions">
			<%=link_to "Войти", log_in_path, :class => "btn success" %> или <%=link_to "Зарегистрироваться", sign_up_path, :class => "btn" %>
            </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Time To Resist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="topbar">
      <div class="fill">
        <div class="container">
          <%=link_to "Time to resist", root_path, :class => "brand"%>
          <ul class="nav">
            <li><%=link_to "Главная", root_path%></li>
            <li><%= link_to "Все наши", users_path%></li>
            <li><%= link_to "Города", cities_path%></li>
          </ul>
          <p class="pull-right">
			  <% if current_user %>
			   <%= link_to  "Привет, "+current_user.email, current_user %>, <%= link_to "(редактировать", edit_user_path(current_user) %> | <%= link_to " выйти)", log_out_path %>!
			  <% else %>
			    <%= link_to "Регистрация", sign_up_path %> |
			    <%= link_to "Вход", log_in_path %>
			  <% end %>
          </p>
        </div>
      </div>
    </div>
	
	<div class="container">
<div class="content">
<% flash.each do |name, msg| %>
<div class="alert-message <%=name%> fade in" data-alert="alert" >
<a class="close" href="#">×</a><p><%=msg%></p>
</div>
<% end %>
<%= yield %>
</div>
<footer>
С предложениями и пожеланиями по дальнейшему развитию сайта к <%= link_to User.find(2).email, User.find(2)%>. <br />
Люди, умеющие рисовать и верстать, пишите так же на почту :) Нужно рисовать/фотошопить наградки и вообще дизайн.
</footer>
<!-- Yandex.Metrika informer --><!--<a href="http://metrika.yandex.ru/stat/?id=11620576&amp;from=informer" target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/11620576/1_1_FFFFFFFF_EFEFEFFF_0_uniques" style="width:80px; height:15px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (уникальные посетители)" /></a> --><!-- /Yandex.Metrika informer --><!-- Yandex.Metrika counter --><div style="display:none;"><script type="text/javascript">(function(w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter11620576 = new Ya.Metrika({id:11620576, clickmap:true, trackLinks:true, webvisor:true}); } catch(e) { } }); })(window, "yandex_metrika_callbacks");</script></div><script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script><noscript><div><img src="//mc.yandex.ru/watch/11620576" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
	</div>
</body>
</html>